project:
    id: 93a2489d193a6a97f8600d36c610be3893dff10694e57bc30ce353fa80c18d50
    name: test
    team: shikigami
    description: mi despliegue con vex
    organization: vex
template:
    url: https://github.com/jairoprogramador/mydeploy.git
    ref: main
runtime:
    image: Dockerfile
    tag: latest
    build:
      args:
        - name: "VEX_VERSION"
          value: "1.0.10"
        - name: "MAVEN_VERSION"
          value: "3.9.12"
    run:
      volumes:
        - host: /home/user/.m2/
          container: /home/ubuntu/.m2
        - host: /home/user/projects/my-project
          container: /home/vex/app
        - host: /home/user/.vex
          container: /home/ubuntu/.vex
      envs:
        - name: "ARM_CLIENT_ID"
          value: "$ARM_CLIENT_ID"
        - name: "ARM_CLIENT_SECRET"
          value: "$ARM_CLIENT_SECRET"
        - name: "ARM_TENANT_ID"
          value: "$ARM_TENANT_ID"
        - name: "ARM_SUBSCRIPTION_ID"
          value: "$ARM_SUBSCRIPTION_ID"
